# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c97db87be8b7c0da7a942bde55734654ae82323ca559485d2da4b9b9fe762369e10ca34095bc737f9b05ebb8c59e49893a7c21511d052f43138403da0b5ebbdc

test:
  secret_key_base: 24f66fc8deb1ac278a405c6611d580f877799ebad75994fcf9d9e23b4175f550324e807e6987ce92971e751f00be7fcaab0405b2c76682bce6ff89d0b11a311e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
