per_page: 12
per_page_comment: 6
limit_categories: 12
email_admin: "cuc12cntt@gmail.com"
email_from: "food.drink.noreply@gmail.com"
subject: "Order mail"
room_id: 57477338
home:
  limit_product: 6
  offset_top_product: 1
  offset_special_product: 7
product:
  truncate_des_product: 50
